function targetEpsr = estimateHomogeneousEpsr( ...
        averageEpsr, backgroundEpsr, numTargetPixels, numBackgroundPixels)
%estimateHomogeneousEpsr Invert the proposed arithmetic pixel mixture.

validateattributes(averageEpsr, {'numeric'}, ...
    {'real', 'finite', 'scalar'}, mfilename, 'averageEpsr');
validateattributes(backgroundEpsr, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'}, mfilename, 'backgroundEpsr');
validateattributes(numTargetPixels, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'positive'}, ...
    mfilename, 'numTargetPixels');
validateattributes(numBackgroundPixels, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'integer', 'nonnegative'}, ...
    mfilename, 'numBackgroundPixels');

numRayPixels = numTargetPixels + numBackgroundPixels;
targetEpsr = (numRayPixels * averageEpsr - ...
    numBackgroundPixels * backgroundEpsr) / numTargetPixels;
end
