function measurement = acquireTransmissionMeasurements(cfg)
%acquireTransmissionMeasurements Measure matched object/reference delays.
% The returned data intentionally contains no true-target geometry.

maximumAngleDegrees = 40;
maximumMatchedDelaySteps = 120;
windowHalfWidthSteps = max(4, round(4*cfg.source.pulseWidth/cfg.dt));

numAntennas = cfg.antennas.numAntennas;
[~, ~, betaTx, betaRx] = buildCircularPairGeometry( ...
    cfg.antennas.pos, cfg.dx, cfg.dy, cfg.antennas.center);
maximumAngle = deg2rad(maximumAngleDegrees);
pairEligible = abs(betaTx) <= maximumAngle & ...
    abs(betaRx) <= maximumAngle;
pairEligible(1:numAntennas+1:end) = false;

matchedDelaySteps = nan(numAntennas);
matchedScores = nan(numAntennas);
simulationTimer = tic;
for tx = 1:numAntennas
    scanCfg = cfg;
    scanCfg.antennas.txAntennas = tx;
    scanCfg.source.samples(:) = 0;
    scanCfg.source.samples(tx, :) = ...
        scanCfg.source.func((0:scanCfg.Nt-1) .* scanCfg.dt);

    rxList = setdiff(1:numAntennas, tx);
    receiverIndices = scanCfg.antennas.pos(rxList, :);
    objectResult = fdtd_mex(scanCfg);
    referenceCfg = fdtdmat.setBackgroundDefault( ...
        scanCfg, scanCfg.grid.background);
    referenceResult = fdtd_mex(referenceCfg);
    [delays, scores] = getMatchedEnvelopeDelaySteps( ...
        objectResult.Ez, referenceResult.Ez, receiverIndices, ...
        referenceCfg, windowHalfWidthSteps, maximumMatchedDelaySteps);

    matchedDelaySteps(tx, rxList) = delays.';
    matchedScores(tx, rxList) = scores.';
    clear objectResult referenceResult
    fprintf('Transmission scan %d/%d complete.\n', tx, numAntennas);
end

measurement = struct( ...
    'gridSize', [cfg.Nx cfg.Ny], ...
    'dx', cfg.dx, 'dy', cfg.dy, 'dt', cfg.dt, 'c0', cfg.c0, ...
    'backgroundEpsr', cfg.grid.background.epsr, ...
    'antennaPositions', cfg.antennas.pos, ...
    'pairEligible', pairEligible, ...
    'matchedDelaySteps', matchedDelaySteps, ...
    'matchedScores', matchedScores, ...
    'maximumAngleDegrees', maximumAngleDegrees, ...
    'maximumMatchedDelaySteps', maximumMatchedDelaySteps, ...
    'windowHalfWidthSteps', windowHalfWidthSteps, ...
    'simulationRunTime', toc(simulationTimer));
end
