function [supportMask, orderedPoints] = buildShapeSupportMask( ...
        focusPoints, doiMask, sigmaThreshold)
%buildShapeSupportMask Fill the same filtered outline used in shape plots.

if nargin < 3 || isempty(sigmaThreshold)
    sigmaThreshold = 1.5;
end
validateattributes(focusPoints, {'numeric'}, ...
    {'real', '2d', 'ncols', 2}, mfilename, 'focusPoints');
validateattributes(doiMask, {'logical'}, {'2d', 'nonempty'}, ...
    mfilename, 'doiMask');
validateattributes(sigmaThreshold, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'positive'}, ...
    mfilename, 'sigmaThreshold');

[doiPoints, doiPointIndices] = ...
    selectShapePointsInsideDoi(double(focusPoints), doiMask);
[inlierPoints, ~, inlierDoiIndices] = ...
    filterShapeOutlinePoints(doiPoints, sigmaThreshold);
orderedPoints = orderShapeOutlinePoints( ...
    inlierPoints, doiPointIndices(inlierDoiIndices));

if size(unique(orderedPoints, 'rows'), 1) < 3 || ...
        polyarea(orderedPoints(:, 1), orderedPoints(:, 2)) <= 0
    error('buildShapeSupportMask:InvalidOutline', ...
        'At least three non-collinear retained focus points are required.');
end

[gridX, gridY] = ndgrid(1:size(doiMask, 1), 1:size(doiMask, 2));
supportMask = inpolygon(gridX, gridY, ...
    orderedPoints(:, 1), orderedPoints(:, 2)) & doiMask;
if ~any(supportMask(:))
    error('buildShapeSupportMask:EmptySupport', ...
        'The estimated outline has no cells inside the DOI.');
end
end
