function newgrid = BlurAndDownsample(highGrid, refine)
%BlurAndDownsample Blur and downsample every material map in a grid struct.
%   This compatibility wrapper delegates to fdtdmat.downsampleCfg so grid
%   construction and staggered material-map handling have one implementation.

if nargin ~= 2
    error('fdtdmat:BlurAndDownsample:InvalidInputCount', ...
        'Expected highGrid and refine inputs.');
end
if ~isstruct(highGrid) || ~isscalar(highGrid) || ...
        ~isfield(highGrid, 'sizeXY') || ...
        ~isfield(highGrid, 'spacingXY') || ...
        ~isfield(highGrid, 'originPhysical') || ...
        ~isfield(highGrid, 'background')
    error('fdtdmat:BlurAndDownsample:InvalidGrid', ...
        ['highGrid must contain sizeXY, spacingXY, originPhysical, ' ...
        'and background fields.']);
end
if ~isnumeric(refine) || ~isscalar(refine) || ~isfinite(refine) || ...
        refine < 1 || refine ~= round(refine) || ...
        any(mod(highGrid.sizeXY, refine) ~= 0)
    error('fdtdmat:BlurAndDownsample:InvalidRefine', ...
        ['refine must be a positive integer that divides both entries ' ...
        'of highGrid.sizeXY.']);
end

temporaryCfg = struct( ...
    'Nx', highGrid.sizeXY(1), ...
    'Ny', highGrid.sizeXY(2), ...
    'dx', highGrid.spacingXY(1), ...
    'dy', highGrid.spacingXY(2), ...
    'grid', highGrid);
coarseCfg = fdtdmat.downsampleCfg(temporaryCfg, refine);
newgrid = coarseCfg.grid;
end
