% compare_fbts_coarsening Compare full-grid and 2x-coarse FBTS sensitivity.
% Builds one configuration, runs 15 iterations for each sensitivity grid,
% and writes both plot_fbts output sets plus comparison artifacts under the
% next figs/comparative_run_XXXX directory.

comparisonScriptPath = mfilename('fullpath');
if isempty(comparisonScriptPath)
    comparisonAlgorithmDirectory = pwd;
else
    comparisonAlgorithmDirectory = fileparts(comparisonScriptPath);
end
addpath(comparisonAlgorithmDirectory, '-begin');

comparisonNumIterations = 15;
comparisonCoarseningFactor = 2;
comparisonOutputDirectory = createNextFbtsOutputDirectory( ...
    fullfile(comparisonAlgorithmDirectory, 'figs'), 'comparative_run');
fprintf('FBTS comparison output: %s\n', comparisonOutputDirectory);

%% Build one shared physical problem for both runs
run(fullfile(comparisonAlgorithmDirectory, 'build_cfg.m'));
comparisonCfg = cfg;

%% Full-resolution directional sensitivity (factor 1)
cfg = comparisonCfg; %#ok<NASGU>
fbtsOptions = struct( ...
    'numIterations', comparisonNumIterations, ...
    'sensitivityDownsampleFactor', 1, ...
    'outputDirectory', string(fullfile( ...
        comparisonOutputDirectory, 'without_coarsening')), ...
    'runLabel', "without coarsening");
fprintf('\nRunning FBTS with sensitivity factor %d (no coarsening).\n', ...
    fbtsOptions.sensitivityDownsampleFactor);
run(fullfile(comparisonAlgorithmDirectory, 'fbts.m'));
uncoarsenedResults = results;
closeFbtsPlotFigures( ...
    [trueFigure estimatedFigure convergenceFigure costFigure]);

%% Four-times-coarser directional sensitivity
cfg = comparisonCfg;
fbtsOptions = struct( ...
    'numIterations', comparisonNumIterations, ...
    'sensitivityDownsampleFactor', comparisonCoarseningFactor, ...
    'outputDirectory', string(fullfile( ...
        comparisonOutputDirectory, sprintf('with_%dx_coarsening', ...
        comparisonCoarseningFactor))), ...
    'runLabel', string(sprintf('with %dx coarsening', ...
        comparisonCoarseningFactor)));
fprintf('\nRunning FBTS with sensitivity factor %d.\n', ...
    fbtsOptions.sensitivityDownsampleFactor);
run(fullfile(comparisonAlgorithmDirectory, 'fbts.m'));
coarsenedResults = results;
closeFbtsPlotFigures( ...
    [trueFigure estimatedFigure convergenceFigure costFigure]);

%% Tabular comparison
variant = ["without coarsening"; string(sprintf( ...
    'with %dx coarsening', comparisonCoarseningFactor))];
sensitivityDownsampleFactor = [ ...
    uncoarsenedResults.sensitivity_downsample_factor; ...
    coarsenedResults.sensitivity_downsample_factor];
sensitivityBaselineStrategy = [ ...
    string(uncoarsenedResults.sensitivity_baseline_strategy); ...
    string(coarsenedResults.sensitivity_baseline_strategy)];
totalRuntimeSeconds = [ ...
    uncoarsenedResults.total_runtime; ...
    coarsenedResults.total_runtime];
averageIterationRuntimeSeconds = [ ...
    uncoarsenedResults.average_runtime; ...
    coarsenedResults.average_runtime];
finalRelativeErrorPercent = [ ...
    uncoarsenedResults.relative_error_percent(end); ...
    coarsenedResults.relative_error_percent(end)];
finalCost = [ ...
    uncoarsenedResults.cost(end); ...
    coarsenedResults.cost(end)];

comparisonSummary = table(variant, sensitivityDownsampleFactor, ...
    sensitivityBaselineStrategy, totalRuntimeSeconds, ...
    averageIterationRuntimeSeconds, finalRelativeErrorPercent, finalCost);
perIterationComparison = table( ...
    uncoarsenedResults.iteration, ...
    uncoarsenedResults.iteration_runtime, ...
    coarsenedResults.iteration_runtime, ...
    uncoarsenedResults.relative_error_percent, ...
    coarsenedResults.relative_error_percent, ...
    uncoarsenedResults.cost, coarsenedResults.cost, ...
    'VariableNames', { ...
        'Iteration', ...
        'RuntimeWithoutCoarseningSeconds', ...
        'RuntimeWith2xCoarseningSeconds', ...
        'ErrorWithoutCoarseningPercent', ...
        'ErrorWith2xCoarseningPercent', ...
        'CostWithoutCoarsening', ...
        'CostWith2xCoarsening'});

runtimeSpeedup = uncoarsenedResults.total_runtime ./ ...
    coarsenedResults.total_runtime;
finalErrorDifferencePercentPoints = ...
    coarsenedResults.relative_error_percent(end) - ...
    uncoarsenedResults.relative_error_percent(end);

%% Comparison figures
runtimeComparisonFigure = figure( ...
    'Name', 'FBTS coarsening runtime comparison', ...
    'NumberTitle', 'off', 'Visible', 'off');
runtimeLayout = tiledlayout(runtimeComparisonFigure, 1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
runtimeTotalAxes = nexttile(runtimeLayout);
bar(runtimeTotalAxes, totalRuntimeSeconds);
set(runtimeTotalAxes, 'XTick', 1:2, ...
    'XTickLabel', {'No coarsening', '2x coarsening'});
ylabel(runtimeTotalAxes, 'Runtime (s)');
title(runtimeTotalAxes, sprintf('Total runtime (speedup %.2fx)', ...
    runtimeSpeedup));
grid(runtimeTotalAxes, 'on');

runtimeIterationAxes = nexttile(runtimeLayout);
plot(runtimeIterationAxes, uncoarsenedResults.iteration, ...
    uncoarsenedResults.iteration_runtime, 'o-', 'LineWidth', 1.2);
hold(runtimeIterationAxes, 'on');
plot(runtimeIterationAxes, coarsenedResults.iteration, ...
    coarsenedResults.iteration_runtime, 's-', 'LineWidth', 1.2);
hold(runtimeIterationAxes, 'off');
xlabel(runtimeIterationAxes, 'FBTS iteration');
ylabel(runtimeIterationAxes, 'Runtime (s)');
title(runtimeIterationAxes, 'Per-iteration runtime');
legend(runtimeIterationAxes, {'No coarsening', '2x coarsening'}, ...
    'Location', 'best');
grid(runtimeIterationAxes, 'on');

errorComparisonFigure = figure( ...
    'Name', 'FBTS coarsening error comparison', ...
    'NumberTitle', 'off', 'Visible', 'off');
errorComparisonAxes = axes('Parent', errorComparisonFigure);
plot(errorComparisonAxes, uncoarsenedResults.iteration, ...
    uncoarsenedResults.relative_error_percent, ...
    'o-', 'LineWidth', 1.2);
hold(errorComparisonAxes, 'on');
plot(errorComparisonAxes, coarsenedResults.iteration, ...
    coarsenedResults.relative_error_percent, ...
    's-', 'LineWidth', 1.2);
hold(errorComparisonAxes, 'off');
xlabel(errorComparisonAxes, 'FBTS iteration');
ylabel(errorComparisonAxes, 'Relative permittivity error (%)');
title(errorComparisonAxes, sprintf( ...
    'Error convergence (final difference %+.3f percentage points)', ...
    finalErrorDifferencePercentPoints));
legend(errorComparisonAxes, {'No coarsening', '2x coarsening'}, ...
    'Location', 'best');
grid(errorComparisonAxes, 'on');

runtimeComparisonFile = fullfile( ...
    comparisonOutputDirectory, 'comparison_runtime.png');
errorComparisonFile = fullfile( ...
    comparisonOutputDirectory, 'comparison_relative_error.png');
exportgraphics(runtimeComparisonFigure, runtimeComparisonFile, ...
    'Resolution', 300);
exportgraphics(errorComparisonFigure, errorComparisonFile, ...
    'Resolution', 300);
closeFbtsPlotFigures([runtimeComparisonFigure errorComparisonFigure]);

%% Persist complete and lightweight comparison data
summaryCsvFile = fullfile( ...
    comparisonOutputDirectory, 'comparison_summary.csv');
perIterationCsvFile = fullfile( ...
    comparisonOutputDirectory, 'comparison_per_iteration.csv');
comparisonMatFile = fullfile( ...
    comparisonOutputDirectory, 'fbts_comparison.mat');
writetable(comparisonSummary, summaryCsvFile);
writetable(perIterationComparison, perIterationCsvFile);
save(comparisonMatFile, 'comparisonCfg', 'uncoarsenedResults', ...
    'coarsenedResults', 'comparisonSummary', ...
    'perIterationComparison', 'runtimeSpeedup', ...
    'finalErrorDifferencePercentPoints', '-v7.3');

fprintf('\nFBTS comparison complete.\n');
fprintf('Runtime speedup with 2x coarsening: %.3fx.\n', runtimeSpeedup);
fprintf('Final error difference: %+.6f percentage points.\n', ...
    finalErrorDifferencePercentPoints);
fprintf('Saved comparison under %s.\n', comparisonOutputDirectory);

clear fbtsOptions activeFbtsOptions

function closeFbtsPlotFigures(figureHandles)
validHandles = figureHandles(isgraphics(figureHandles));
if ~isempty(validHandles)
    close(validHandles);
end
end
