function row = fbtsBatchSummaryRow()
%fbtsBatchSummaryRow Stable CSV/status schema, including unavailable statistics.
row = struct('run_index',NaN,'scene_id',"",'class_id',"", ...
    'num_active_antennas',NaN,'active_antenna_indices',"",'disabled_antenna_indices',"", ...
    'orbit_size',NaN,'rotation',NaN,'reflected',false,'first_transmitter',NaN, ...
    'num_iterations',NaN,'completed_iterations',0,'output_directory',"",'result_file',"", ...
    'status',"queued",'failure_stage',"",'error_id',"",'error_message',"", ...
    'started_utc',"",'finished_utc',"",'result_hash',"",'acquisition_cache_hit',true, ...
    'queue_wait_seconds',NaN,'setup_seconds',NaN,'fbts_seconds',NaN,'inversion_seconds',NaN, ...
    'save_seconds',NaN,'hash_seconds',NaN,'plot_seconds',0,'run_total_seconds',NaN,'plot_error',"");
phases = {'measurement','forward','adjoint','sensitivity_baseline','sensitivity_perturbation'};
statistics = {'count','first_seconds','min_seconds','max_seconds','mean_seconds', ...
    'median_seconds','std_seconds','variance_seconds2','total_seconds'};
for phase = phases
    for statistic = statistics, row.(['fdtd_' phase{1} '_' statistic{1}]) = NaN; end
end
end
