function saveFbtsBatchCase(path, cfg, results, caseInfo, options)
%saveFbtsBatchCase Analysis schema; no duplicated truth/measurements or quality metrics.
mask = logical(cfg.antennas.doiMask);
parameters = struct('fbts_options',options,'epsr_lower_bound',results.epsr_lower_bound, ...
    'initialization','epsr_background','estimated_properties',{{'epsr'}}, ...
    'direction','bound-projected Polak-Ribiere-Polyak', ...
    'finite_difference_scale',1e-3,'alpha_rule','max(step_q/step_a,0)', ...
    'projection','epsr >= 1 inside DOI; prescribed background outside', ...
    'self_receiver_included',true,'state_convention','iteration j evaluates state j-1 then produces state j');
payload = struct('schema_version',1,'caseInfo',caseInfo,'parameters',parameters, ...
    'epsr_est',results.epsr_est,'epsr_history_doi',results.epsr_history_doi, ...
    'history',results.history,'rx_model_history',results.rx_model_history, ...
    'rx_sensitivity_coarse_history',results.rx_sensitivity_coarse_history, ...
    'gradient_raw_doi_last',results.raw_gradient_epsr(mask), ...
    'gradient_projected_doi_last',results.gradient_epsr(mask), ...
    'direction_doi_last',results.direction_epsr(mask), ...
    'last_evaluated_state_index',results.num_iterations-1,'timing',results.timing);
saveFbtsAtomic(path,payload);
end
