function selected = selectFbtsMeasurements(measurements, cfg)
%selectFbtsMeasurements Validate and map original TX/RX IDs without squeezing.
m = measurements.metadata;
assert(m.complete && strcmp(m.fingerprint, fbtsHash(rmfield(m, 'fingerprint'))), ...
    'fbts:InvalidMeasurements', 'Incomplete or modified measurement metadata.');
identity = fbtsAcquisitionIdentity(cfg);
assert(strcmp(m.identity.physics_hash, identity.physics_hash), ...
    'fbts:MeasurementMismatch', 'Scene, grid, pulse, boundary, or solver differs.');
assert(isequal(m.time, identity.time) && ...
    size(measurements.rx,1) == numel(m.tx_ids) && ...
    size(measurements.rx,2) == numel(m.rx_ids) && ...
    size(measurements.rx,3) == cfg.Nt && ...
    all(isfinite(measurements.rx), 'all') && ...
    strcmp(m.rx_hash, fbtsHash(measurements.rx)), ...
    'fbts:InvalidMeasurements', 'Measurement dimensions, samples, or checksum are invalid.');
n = cfg.antennas.numAntennas;
original = 1:n;
if isfield(cfg.antennas, 'originalIndices'), original = cfg.antennas.originalIndices; end
[foundTx, tx] = ismember(original(cfg.antennas.txAntennas), m.tx_ids);
[foundRx, rx] = ismember(original, m.rx_ids);
assert(all(foundTx) && all(foundRx) && numel(unique(original)) == n, ...
    'fbts:MeasurementMismatch', 'Requested original antenna IDs are missing or duplicated.');
assert(isequal(m.tx_positions(tx,:), cfg.antennas.pos(cfg.antennas.txAntennas,:)) && ...
    isequal(m.rx_positions(rx,:), cfg.antennas.pos), ...
    'fbts:MeasurementMismatch', 'Antenna IDs refer to different positions.');
selected = measurements.rx(tx, rx, :);
end
