function validateFbtsScene(cfg, options)
%validateFbtsScene Explicit assumptions of this lossless permittivity batch.
assert(isstruct(cfg) && isscalar(cfg),'fbts:InvalidScene','Expected one configuration.');
assert(isequal(size(cfg.grid.epsr),[cfg.Nx cfg.Ny]) && ...
    isequal(size(cfg.grid.epsr_bg),[cfg.Nx cfg.Ny]) && ...
    all(isfinite(cfg.grid.epsr),'all') && all(cfg.grid.epsr>=1,'all') && ...
    all(isfinite(cfg.grid.epsr_bg),'all') && all(cfg.grid.epsr_bg>=1,'all'), ...
    'fbts:InvalidScene','Permittivity maps must be finite, aligned, and at least one.');
assert(all(cfg.grid.cond_e==0,'all') && all(cfg.grid.cond_m==0,'all') && ...
    all(cfg.grid.murx==1,'all') && all(cfg.grid.mury==1,'all') && ...
    all(cfg.grid.cond_e_bg==0,'all') && all(cfg.grid.cond_m_bg==0,'all') && ...
    all(cfg.grid.murx_bg==1,'all') && all(cfg.grid.mury_bg==1,'all'), ...
    'fbts:UnsupportedMaterial','Batch currently reconstructs lossless nonmagnetic permittivity only.');
assert(isfield(cfg,'targets'),'fbts:MissingTargets','Provide target geometry/masks with the scene.');
assert(isequal(size(cfg.antennas.doiMask),[cfg.Nx cfg.Ny]) && any(cfg.antennas.doiMask,'all'), ...
    'fbts:InvalidDOI','The DOI must be nonempty and match the grid.');
outside = ~logical(cfg.antennas.doiMask);
assert(isequal(cfg.grid.epsr(outside),cfg.grid.epsr_bg(outside)), ...
    'fbts:TargetOutsideDOI','True permittivity outside the DOI must equal the prescribed background.');
assert(cfg.snapshotStart==0 && cfg.snapshotStride==1, ...
    'fbts:InvalidSnapshots','FBTS requires every forward field time sample, starting at zero.');
if isfield(cfg,'init')
    assert(all(cfg.init.Ez==0,'all') && all(cfg.init.Hx==0,'all') && all(cfg.init.Hy==0,'all'), ...
        'fbts:UnsupportedInitialState','Batch inversion currently requires zero initial fields.');
end
assert(isequal(cfg.antennas.txAntennas,1:cfg.antennas.numAntennas), ...
    'fbts:InvalidTransmitters','A scene must provide the full original TX array in ascending order.');
if isfield(cfg.antennas,'originalIndices')
    assert(isequal(cfg.antennas.originalIndices,1:cfg.antennas.numAntennas), ...
        'fbts:InvalidScene','Supply a full array, not an already reduced case.');
end
prepareFbtsSource(cfg);
prepareCoarseSensitivityCfg(cfg,options.sensitivityDownsampleFactor);
end
